Fix nushell integration
asdf-vm/asdf pull request #1624
Opened 2023-09-01 08:18 UTC by lorenzk

# Summary

Nushell integration is broken because of the deprecated `let-env`, see https://www.nushell.sh/commands/docs/let-env.html#frontmatter-title-for-removed for details.

Fixes: #1609 

## Other Information

There is already pull request #1610 that does not seem to be worked on at the moment.

Manual testing on my MacBook M1 worked. I tried running the automated test suite, but there were too many unrelated errors. I hope your CI will tell us whether I did everything right.

Linting worked.

2023-09-01 08:54 UTC, lorenzk commented
I made a mistake that I only noticed after restarting my iTerm2. Fixed it in the third commit, but did not rebase or anything to keep things in historical order. Feel free to merge/squash however you like.

2023-09-08 02:04 UTC, hyperupcall requested changes
Thanks! When I test the changes, I recieve two errors: One I commented about and another about the `^asdf syntax`. I'm not able to run CI here, but you can see the output from [one of my forks](https://github.com/fox-brewery/asdf/actions/runs/6116729045?pr=7). The only difference is that I squashed your changes.


About the [`^asdf` syntax](https://github.com/lorenzk/asdf/blob/6ac72ceedb5193fb0f95fd82ad04ae82deb461e7/asdf.nu#L107), it seems that it is supposed to refer to the current module, but it does not seem to work anymore. I get the error:

```text
# × External command failed
#      ╭─[/Users/runner/work/asdf/asdf/asdf.nu:98:1]
#   98 │
#   99 │         ^asdf plugin list $flags | lines | parse -r $template | str trim
#      ·          ──┬─
#      ·            ╰── command 'asdf' was not found but it exists in module 'asdf'; try importing it with `use`
#  100 │     }
#      ╰────
```

2023-09-10 14:25 UTC, jthegedus requested changes
Before we can merge this can you @lorenzk address the comment from @hyperupcall ?

2023-09-11 10:58 UTC, jthegedus commented on asdf.nu
> +    $env.ASDF_NU_DIR = (brew --prefix asdf | str trim | into string | path join 'libexec')
So I believe this `ASDF_NU_DIR` was a way for users to override the default dir from outside this script. Upon commenting it out the test cases passed. I have subsequently removed this line and will merge momentarily.

2023-09-11 10:58 UTC, jthegedus approved these changes
Thanks

2023-09-11 11:02 UTC, merged

2023-09-11 11:08 UTC, lorenzk commented
Sorry for not replying earlier. You're awesome, thanks! Assuming `brew` to exist made no sense at all on my part.

2023-09-11 11:14 UTC, jthegedus commented
> Sorry for not replying earlier. You're awesome, thanks! Assuming `brew` to exist made no sense at all on my part.

All good mate, you did the heavy lifting, much appreciated 🙇