Bash Strict Mode: Part 1 of 3
asdf-vm/asdf pull request #817
Opened 2020-10-16 15:14 UTC by Stratus3D

# Summary

Instead of implementing Bash strict mode in one pull request (as I tried to do with #520 and failed) I am going to do it in three parts:

* Don't allow unset variables (this PR)
* Exit on non-zero exit codes (including in pipes)
* Set a stricter IFS

This PR addresses part of #160

2020-10-16 15:18 UTC, Stratus3D commented on lib/commands/command-reshim.bash
> +    asdf_run_hook "post_asdf_reshim_$plugin_name" "$full_version_name"
This was actually a bug! These functions were invoked in a way that was inconsistent with the code in the `else` block below.

2020-10-16 15:18 UTC, Stratus3D commented on test/shim_env_command.bats
> -  [ "$duplicate_colon" == "" ]
Another bug. This variable was never set so this line wasn't actually testing anything.

2020-10-16 15:19 UTC, Stratus3D commented on test/utils.bats
> -  cd $outer
Another test that wasn't testing what it was suppose to because of an unset variable.

2020-11-09 04:30 UTC, jthegedus commented
looking over this now :)

2020-11-09 14:35 UTC, Stratus3D commented
@jthegedus build is failing right now. I created this PR on my OSX machine but it looks like things aren't working on Ubuntu. I'm going pull these changes down on my Ubuntu machine and resume working through the remaining issues. I probably won't get to this until late next week though.

2020-11-10 09:03 UTC, jthegedus commented
No problem. This is a good start to enabling strict mode. I like this process has revealed bugs, proves the effort is valid :smile:

2020-11-10 09:08 UTC, jthegedus commented on lib/commands/command-env.bash
> +    "$env_cmd" ${env_args[@]+"${env_args[@]}"}
In an effort to capture minimum versions we support, I would like capture the min Bash version that supports this in the docs if we could

2020-11-10 09:09 UTC, jthegedus approved these changes

2021-05-27 01:42 UTC, jthegedus requested changes
Hey mate, can this be re-based? If I recall it was pretty close to done.

2021-05-27 13:12 UTC, Stratus3D commented
> Hey mate, can this be re-based? If I recall it was pretty close to done.

Yes, this is next on my agenda. I will rebase and try to fix the failing tests on Ubuntu tomorrow.

2022-05-17 13:30 UTC, Stratus3D commented
I just rebased this PR onto latest master. I'm hoping to finish this PR update and get it merged soon.

2022-05-18 00:47 UTC, jthegedus commented
Tag me when you wish to have a review.

2023-04-05 14:27 UTC, jthegedus commented
I am not sure if we can automate some of these fixes with Shellcheck/Shfmt, but perhaps these proposed changes can be enforced (and potentially auto-fixed) by expanding `scripts/stylecheck.py`?

2023-06-18 07:34 UTC, jthegedus commented
@Stratus3D should we close this?

2023-06-19 05:13 UTC, hyperupcall commented
We can definitely add some stuff to `checkstyle.py` to prepare things for `set -u`, and I feel reluctant to say this to a 3-year old PR adding this stuff, but in my opinion, `errunset` is more trouble than it's worth, especially with ShellCheck.

Unfortunately, I can't think of any way to add the latter two to `checkstyle.py`, but maybe there is a way.

2023-06-22 16:12 UTC, jthegedus commented
@hyperupcall I'm very happy with the level of code quality improvements you have brought to the project over the past year. I don't think this is worth tackling (and assumed Stratus would agree), so thought I would just ask before closing it.

I will just close it though as I think we're all better off spending our time on other issues than this in the short term. We can always dig it back up should we want.

2023-06-22 16:12 UTC, closed without merging

2023-07-12 20:53 UTC, Stratus3D commented
Thanks @jthegedus. I don't have plans to tackle this anymore. I'm focusing my effort on the Rust rewrite.